<?php

return [
    'city_order' => [
        'boston',
        'cambridge',
        'everett',
        'chicago',
        'san_francisco',
        'seattle',
        'montgomery_county_md',
        'new_york',
    ],

    'cities' => [
        'boston' => [
            'label' => 'Boston',
            'description' => "Select specific datasets and/or seeders. Leave blank to run all items in the selected 'Boston' stages.",
            'acquisition' => [
                'stage' => 'Boston Data Acquisition',
                'label' => 'Boston Datasets',
                'parameter' => 'bostonDatasets',
                'option' => 'boston-datasets',
                'option_description' => 'Comma-separated list of Boston dataset names to download',
                'source' => 'boston_datasets',
                'mode' => 'batch_download',
                'command' => 'app:download-boston-dataset-via-scraper',
                'command_parameter' => '--names',
            ],
            'seeding' => [
                'stage' => 'Boston Data Seeding',
                'label' => 'Boston Seeders',
                'parameter' => 'bostonSeeders',
                'option' => 'boston-seeders',
                'option_description' => 'Comma-separated list of Boston seeder classes to run',
                'items' => [
                    ['name' => 'TrashSchedulesByAddressSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'TrashSchedulesByAddressSeeder', '--force' => true]],
                    ['name' => 'CrimeDataSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'CrimeDataSeeder', '--force' => true]],
                    ['name' => 'ThreeOneOneSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'ThreeOneOneSeeder', '--force' => true]],
                    ['name' => 'BuildingPermitsSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'BuildingPermitsSeeder', '--force' => true]],
                    ['name' => 'PropertyViolationsSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'PropertyViolationsSeeder', '--force' => true]],
                    ['name' => 'ConstructionOffHoursSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'ConstructionOffHoursSeeder', '--force' => true]],
                    ['name' => 'FoodInspectionsSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'FoodInspectionsSeeder', '--force' => true]],
                ],
            ],
        ],
        'cambridge' => [
            'label' => 'Cambridge',
            'description' => 'Select specific acquisition commands and/or seeders for Cambridge.',
            'acquisition' => [
                'stage' => 'Cambridge Data Acquisition',
                'label' => 'Cambridge Datasets',
                'parameter' => 'cambridgeDatasets',
                'option' => 'cambridge-datasets',
                'option_description' => 'Comma-separated list of Cambridge acquisition commands or dataset names to run',
                'source' => 'datasets',
                'city' => 'cambridge',
                'extra_items' => [
                    ['name' => 'app:download-cambridge-logs', 'command' => 'app:download-cambridge-logs', 'params' => []],
                ],
            ],
            'seeding' => [
                'stage' => 'Cambridge Data Seeding',
                'label' => 'Cambridge Seeders',
                'parameter' => 'cambridgeSeeders',
                'option' => 'cambridge-seeders',
                'option_description' => 'Comma-separated list of Cambridge seeder classes to run',
                'items' => [
                    ['name' => 'NativeCambridgeBuildingPermitsSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'NativeCambridgeBuildingPermitsSeeder', '--force' => true]],
                    ['name' => 'NativeCambridgeThreeOneOneSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'NativeCambridgeThreeOneOneSeeder', '--force' => true]],
                    ['name' => 'NativeCambridgeSanitaryInspectionsSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'NativeCambridgeSanitaryInspectionsSeeder', '--force' => true]],
                    ['name' => 'NativeCambridgeHousingViolationsSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'NativeCambridgeHousingViolationsSeeder', '--force' => true]],
                    ['name' => 'CambridgeAddressesSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'CambridgeAddressesSeeder', '--force' => true]],
                    ['name' => 'CambridgeIntersectionsSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'CambridgeIntersectionsSeeder', '--force' => true]],
                    ['name' => 'CambridgeCrimeDataSeederMerge', 'command' => 'db:seed', 'params' => ['--class' => 'CambridgeCrimeDataSeederMerge', '--force' => true]],
                    ['name' => 'CambridgePoliceLogSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'CambridgePoliceLogSeeder', '--force' => true]],
                ],
            ],
        ],
        'everett' => [
            'label' => 'Everett',
            'description' => 'Select specific processing steps and/or seeders for Everett.',
            'acquisition' => [
                'stage' => 'Everett Data Acquisition & Processing',
                'label' => 'Everett Steps',
                'parameter' => 'everettSteps',
                'option' => 'everett-steps',
                'option_description' => 'Comma-separated list of Everett processing commands to run',
                'items' => [
                    ['name' => 'app:download-everett-pdf-markdown', 'command' => 'app:download-everett-pdf-markdown', 'params' => []],
                    ['name' => 'everett:process-data', 'command' => 'everett:process-data', 'params' => ['api' => 'places']],
                    ['name' => 'app:generate-everett-csv', 'command' => 'app:generate-everett-csv', 'params' => []],
                ],
            ],
            'seeding' => [
                'stage' => 'Everett Data Seeding',
                'label' => 'Everett Seeders',
                'parameter' => 'everettSeeders',
                'option' => 'everett-seeders',
                'option_description' => 'Comma-separated list of Everett seeder classes to run',
                'items' => [
                    ['name' => 'EverettCrimeDataSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'EverettCrimeDataSeeder', '--force' => true]],
                ],
            ],
        ],
        'chicago' => [
            'label' => 'Chicago',
            'description' => 'Select specific datasets and/or seeders for Chicago.',
            'acquisition' => [
                'stage' => 'Chicago Data Acquisition',
                'label' => 'Chicago Datasets',
                'parameter' => 'chicagoDatasets',
                'option' => 'chicago-datasets',
                'option_description' => 'Comma-separated list of Chicago dataset names to download',
                'source' => 'datasets',
                'city' => 'chicago',
            ],
            'seeding' => [
                'stage' => 'Chicago Data Seeding',
                'label' => 'Chicago Seeders',
                'parameter' => 'chicagoSeeders',
                'option' => 'chicago-seeders',
                'option_description' => 'Comma-separated list of Chicago seeder classes to run',
                'items' => [
                    ['name' => 'ChicagoCrimeSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'ChicagoCrimeSeeder', '--force' => true]],
                    ['name' => 'ChicagoDataPointSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'ChicagoDataPointSeeder', '--force' => true]],
                ],
            ],
        ],
        'san_francisco' => [
            'label' => 'San Francisco',
            'description' => 'Select specific datasets and/or seeders for San Francisco.',
            'acquisition' => [
                'stage' => 'San Francisco Data Acquisition',
                'label' => 'San Francisco Datasets',
                'parameter' => 'sanFranciscoDatasets',
                'option' => 'san-francisco-datasets',
                'option_description' => 'Comma-separated list of San Francisco dataset names to download',
                'source' => 'datasets',
                'city' => 'san_francisco',
            ],
            'seeding' => [
                'stage' => 'San Francisco Data Seeding',
                'label' => 'San Francisco Seeders',
                'parameter' => 'sanFranciscoSeeders',
                'option' => 'san-francisco-seeders',
                'option_description' => 'Comma-separated list of San Francisco seeder classes to run',
                'items' => [
                    ['name' => 'SanFranciscoCrimeSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'SanFranciscoCrimeSeeder', '--force' => true]],
                    ['name' => 'SanFranciscoDataPointSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'SanFranciscoDataPointSeeder', '--force' => true]],
                ],
            ],
        ],
        'seattle' => [
            'label' => 'Seattle',
            'description' => 'Select specific datasets and/or seeders for Seattle.',
            'acquisition' => [
                'stage' => 'Seattle Data Acquisition',
                'label' => 'Seattle Datasets',
                'parameter' => 'seattleDatasets',
                'option' => 'seattle-datasets',
                'option_description' => 'Comma-separated list of Seattle dataset names to download',
                'source' => 'datasets',
                'city' => 'seattle',
            ],
            'seeding' => [
                'stage' => 'Seattle Data Seeding',
                'label' => 'Seattle Seeders',
                'parameter' => 'seattleSeeders',
                'option' => 'seattle-seeders',
                'option_description' => 'Comma-separated list of Seattle seeder classes to run',
                'items' => [
                    ['name' => 'SeattleCrimeSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'SeattleCrimeSeeder', '--force' => true]],
                    ['name' => 'SeattleDataPointSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'SeattleDataPointSeeder', '--force' => true]],
                ],
            ],
        ],
        'montgomery_county_md' => [
            'label' => 'Montgomery County MD',
            'description' => 'Select specific datasets and/or seeders for Montgomery County MD.',
            'acquisition' => [
                'stage' => 'Montgomery County MD Data Acquisition',
                'label' => 'Montgomery County MD Datasets',
                'parameter' => 'montgomeryCountyMdDatasets',
                'option' => 'montgomery-county-md-datasets',
                'option_description' => 'Comma-separated list of Montgomery County MD dataset names to download',
                'source' => 'datasets',
                'city' => 'montgomery_county_md',
            ],
            'seeding' => [
                'stage' => 'Montgomery County MD Data Seeding',
                'label' => 'Montgomery County MD Seeders',
                'parameter' => 'montgomeryCountyMdSeeders',
                'option' => 'montgomery-county-md-seeders',
                'option_description' => 'Comma-separated list of Montgomery County MD seeder classes to run',
                'items' => [
                    ['name' => 'MontgomeryCountyMdCrimeSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'MontgomeryCountyMdCrimeSeeder', '--force' => true]],
                    ['name' => 'MontgomeryCountyMdDataPointSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'MontgomeryCountyMdDataPointSeeder', '--force' => true]],
                ],
            ],
        ],
        'new_york' => [
            'label' => 'New York',
            'description' => 'Select specific datasets and/or seeders for New York.',
            'acquisition' => [
                'stage' => 'New York Data Acquisition',
                'label' => 'New York Datasets',
                'parameter' => 'newYorkDatasets',
                'option' => 'new-york-datasets',
                'option_description' => 'Comma-separated list of New York dataset names to download',
                'source' => 'datasets',
                'city' => 'new_york',
            ],
            'seeding' => [
                'stage' => 'New York Data Seeding',
                'label' => 'New York Seeders',
                'parameter' => 'newYorkSeeders',
                'option' => 'new-york-seeders',
                'option_description' => 'Comma-separated list of New York seeder classes to run',
                'items' => [
                    ['name' => 'NewYork311Seeder', 'command' => 'db:seed', 'params' => ['--class' => 'NewYork311Seeder', '--force' => true]],
                    ['name' => 'NewYorkDataPointSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'NewYorkDataPointSeeder', '--force' => true]],
                ],
            ],
        ],
    ],

    'general_sections' => [
        [
            'label' => 'Post-Seeding Steps',
            'description' => 'Select specific aggregation and caching steps.',
            'stage' => 'Post-Seeding Aggregation & Caching',
            'parameter' => 'postSeedingSteps',
            'option' => 'post-seeding-steps',
            'option_description' => 'Comma-separated list of post-seeding commands to run',
            'items' => [
                ['name' => 'DataPointSeeder', 'command' => 'db:seed', 'params' => ['--class' => 'DataPointSeeder', '--force' => true]],
                ['name' => 'app:cache-metrics-data', 'command' => 'app:cache-metrics-data', 'params' => []],
            ],
        ],
        [
            'label' => 'Reporting Steps',
            'description' => 'Select specific reporting commands.',
            'stage' => 'Reporting',
            'parameter' => 'reportingSteps',
            'option' => 'reporting-steps',
            'option_description' => 'Comma-separated list of reporting commands to run',
            'items' => [
                ['name' => 'reports:send', 'command' => 'reports:send', 'params' => []],
            ],
        ],
    ],
];
