<?php

return [
    'file_targets' => [
        [
            'slug' => 'logs',
            'name' => 'All Logs',
            'default' => true,
            'paths' => [
                storage_path('logs'),
            ],
        ],
        [
            'slug' => 'laravel-current-log',
            'name' => 'Current Laravel Log',
            'default' => false,
            'paths' => [
                storage_path('logs/laravel.log'),
            ],
        ],
        [
            'slug' => 'laravel-log-archives',
            'name' => 'Archived Laravel Logs',
            'default' => false,
            'paths' => [
                storage_path('logs'),
            ],
            'include_patterns' => [
                'laravel.log.*',
                'laravel-*.log',
            ],
        ],
        [
            'slug' => 'pipeline-runs',
            'name' => 'Pipeline Run Logs',
            'default' => false,
            'paths' => [
                storage_path('logs/pipeline_runs'),
            ],
        ],
        [
            'slug' => 'datasets',
            'name' => 'All Downloaded Datasets',
            'default' => true,
            'paths' => [
                storage_path('app/datasets'),
            ],
        ],
        [
            'slug' => 'boston-datasets',
            'name' => 'Boston Full Snapshot Datasets',
            'default' => false,
            'paths' => [
                storage_path('app/datasets'),
            ],
            'include_patterns' => [
                '311-service-requests-2025_*.csv',
                '311-service-requests-2026_*.csv',
                '311-service-requests-new-system_*.csv',
                'construction-off-hours_*.csv',
                'building-permits_*.csv',
                'crime-incident-reports_*.csv',
                'trash-schedules-by-address_*.csv',
                'property-violations_*.csv',
                'food-inspections_*.csv',
            ],
        ],
        [
            'slug' => 'cambridge-datasets',
            'name' => 'Cambridge Datasets',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/cambridge'),
            ],
        ],
        [
            'slug' => 'cambridge-socrata-datasets',
            'name' => 'Cambridge Socrata Snapshots',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/cambridge'),
            ],
            'exclude_paths' => [
                storage_path('app/datasets/cambridge/logs'),
            ],
        ],
        [
            'slug' => 'cambridge-logs',
            'name' => 'Cambridge Daily Police Logs',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/cambridge/logs'),
            ],
        ],
        [
            'slug' => 'chicago-datasets',
            'name' => 'Chicago Datasets',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/chicago'),
            ],
        ],
        [
            'slug' => 'montgomery-county-md-datasets',
            'name' => 'Montgomery County MD Datasets',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/montgomery_county_md'),
            ],
        ],
        [
            'slug' => 'massachusetts-datasets',
            'name' => 'Massachusetts Datasets',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/massachusetts'),
            ],
        ],
        [
            'slug' => 'san-francisco-datasets',
            'name' => 'San Francisco Datasets',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/san_francisco'),
            ],
        ],
        [
            'slug' => 'seattle-datasets',
            'name' => 'Seattle Datasets',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/seattle'),
            ],
        ],
        [
            'slug' => 'new-york-datasets',
            'name' => 'New York Datasets',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/new_york'),
            ],
        ],
        [
            'slug' => 'everett-datasets',
            'name' => 'Everett Datasets',
            'default' => false,
            'paths' => [
                storage_path('app/datasets/everett'),
            ],
        ],
    ],

    'database_apply_batch_size' => (int) env('DATA_RETENTION_DATABASE_APPLY_BATCH_SIZE', 1000),

    'automation' => [
        'enabled' => filter_var(env('DATA_RETENTION_AUTOMATION_ENABLED', false), FILTER_VALIDATE_BOOL),
        'day_of_week' => (int) env('DATA_RETENTION_AUTOMATION_DAY_OF_WEEK', 0),
        'time' => env('DATA_RETENTION_AUTOMATION_TIME', '03:30'),
        'timezone' => env('DATA_RETENTION_AUTOMATION_TIMEZONE', env('APP_TIMEZONE', 'America/New_York')),
        'groups' => array_values(array_filter(array_map(
            static fn (string $group) => trim($group),
            explode(',', (string) env('DATA_RETENTION_AUTOMATION_GROUPS', 'main_raw_source_tables'))
        ))),
        'batch_size' => (int) env(
            'DATA_RETENTION_AUTOMATION_BATCH_SIZE',
            env('DATA_RETENTION_DATABASE_APPLY_BATCH_SIZE', 1000)
        ),
    ],

    'database_rules' => [
        [
            'slug' => 'shared-data-points',
            'name' => 'Shared Data Points',
            'group' => 'aggregated_data_points',
            'connection' => 'mysql',
            'table' => 'data_points',
            'date_field' => 'alcivartech_date',
            'retention_days' => 183,
            'delete_key' => 'id',
            'sample_columns' => ['type', 'generic_foreign_id', 'alcivartech_date'],
            'notes' => 'Already pruned during daily seeding; keep here for preview parity and manual cleanup.',
        ],
        [
            'slug' => 'chicago-data-points',
            'name' => 'Chicago Data Points',
            'group' => 'aggregated_data_points',
            'connection' => 'chicago_db',
            'table' => 'chicago_data_points',
            'date_field' => 'alcivartech_date',
            'retention_days' => 183,
            'delete_key' => 'id',
            'sample_columns' => ['type', 'generic_foreign_id', 'alcivartech_date'],
        ],
        [
            'slug' => 'san-francisco-data-points',
            'name' => 'San Francisco Data Points',
            'group' => 'aggregated_data_points',
            'connection' => 'san_francisco_db',
            'table' => 'san_francisco_data_points',
            'date_field' => 'alcivartech_date',
            'retention_days' => 183,
            'delete_key' => 'id',
            'sample_columns' => ['type', 'generic_foreign_id', 'alcivartech_date'],
        ],
        [
            'slug' => 'seattle-data-points',
            'name' => 'Seattle Data Points',
            'group' => 'aggregated_data_points',
            'connection' => 'seattle_db',
            'table' => 'seattle_data_points',
            'date_field' => 'alcivartech_date',
            'retention_days' => 183,
            'delete_key' => 'id',
            'sample_columns' => ['type', 'generic_foreign_id', 'alcivartech_date'],
        ],
        [
            'slug' => 'montgomery-county-md-data-points',
            'name' => 'Montgomery County MD Data Points',
            'group' => 'aggregated_data_points',
            'connection' => 'montgomery_county_md_db',
            'table' => 'montgomery_county_md_data_points',
            'date_field' => 'alcivartech_date',
            'retention_days' => 183,
            'delete_key' => 'id',
            'sample_columns' => ['type', 'generic_foreign_id', 'alcivartech_date'],
        ],
        [
            'slug' => 'new-york-data-points',
            'name' => 'New York Data Points',
            'group' => 'aggregated_data_points',
            'connection' => 'new_york_db',
            'table' => 'new_york_data_points',
            'date_field' => 'alcivartech_date',
            'retention_days' => 183,
            'delete_key' => 'id',
            'sample_columns' => ['type', 'generic_foreign_id', 'alcivartech_date'],
        ],
        [
            'slug' => 'crime-data',
            'name' => 'Boston Crime Data',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'crime_data',
            'date_field' => 'occurred_on_date',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['incident_number', 'offense_code_group', 'occurred_on_date'],
            'notes' => 'Operational table for the recent analysis window; one-year retention matches current product freshness needs.',
        ],
        [
            'slug' => 'three-one-one-cases',
            'name' => 'Boston 311 Cases',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'three_one_one_cases',
            'date_field' => 'open_dt',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['case_enquiry_id', 'case_status', 'open_dt'],
        ],
        [
            'slug' => 'property-violations',
            'name' => 'Boston Property Violations',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'property_violations',
            'date_field' => 'status_dttm',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['case_no', 'status', 'status_dttm'],
        ],
        [
            'slug' => 'construction-off-hours',
            'name' => 'Boston Construction Off-Hours',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'construction_off_hours',
            'date_field' => 'start_datetime',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['app_no', 'address', 'start_datetime'],
        ],
        [
            'slug' => 'building-permits',
            'name' => 'Boston Building Permits',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'building_permits',
            'date_field' => 'issued_date',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['permitnumber', 'status', 'issued_date'],
        ],
        [
            'slug' => 'food-inspections',
            'name' => 'Boston Food Inspections',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'food_inspections',
            'date_field' => 'resultdttm',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['businessname', 'result', 'resultdttm'],
        ],
        [
            'slug' => 'cambridge-311-service-requests',
            'name' => 'Cambridge 311 Service Requests',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'cambridge_311_service_requests',
            'date_field' => 'ticket_created_date_time',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['ticket_id_external', 'ticket_status', 'ticket_created_date_time'],
        ],
        [
            'slug' => 'cambridge-building-permits',
            'name' => 'Cambridge Building Permits',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'cambridge_building_permits_data',
            'date_field' => 'issue_date',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['permit_id_external', 'status', 'issue_date'],
        ],
        [
            'slug' => 'cambridge-crime-reports',
            'name' => 'Cambridge Crime Reports',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'cambridge_crime_reports_data',
            'date_field' => 'crime_start_time',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['file_number_external', 'crime', 'crime_start_time'],
        ],
        [
            'slug' => 'cambridge-housing-violations',
            'name' => 'Cambridge Housing Violations',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'cambridge_housing_violation_data',
            'date_field' => 'issue_date',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['record_id_external', 'status', 'issue_date'],
        ],
        [
            'slug' => 'cambridge-sanitary-inspections',
            'name' => 'Cambridge Sanitary Inspections',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'cambridge_sanitary_inspection_data',
            'date_field' => 'date_cited',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['case_number_group', 'code_case_status', 'date_cited'],
        ],
        [
            'slug' => 'person-crash-data',
            'name' => 'Massachusetts Person Crash Data',
            'group' => 'main_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'person_crash_data',
            'date_field' => 'crash_datetime',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['crash_person_id', 'city_town_name', 'crash_datetime'],
            'notes' => 'Keep one year in the operational database; older history should live in artifacts or exports if needed later.',
        ],
        [
            'slug' => 'everett-crime-data',
            'name' => 'Everett Crime Data',
            'group' => 'full_history_raw_source_tables',
            'connection' => 'mysql',
            'table' => 'everett_crime_data',
            'date_field' => 'occurred_on_datetime',
            'retention_days' => 365,
            'delete_key' => 'id',
            'sample_columns' => ['case_number', 'incident_type', 'occurred_on_datetime'],
            'notes' => 'Everett raw history is intentionally kept in full for now, so it stays out of the main raw-table retention group.',
        ],
    ],
];
